# Generated by Django 5.1.1 on 2025-06-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0007_delete_film_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isoform', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
