# Generated by Django 5.1.1 on 2025-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0008_transcriptcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isoform', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('counts', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TranscriptCategory',
        ),
    ]
